AWSTemplateFormatVersion: '2010-09-09'
Description: 'Backend Infrastructure: ECS Fargate and API Gateway scaffold'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where ECS will run
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs for ECS Tasks
  DatabaseUrl:
    Type: String
    Description: RDS Database URL (jdbc:mysql://...)

Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: backend-cluster

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: backend-app
          Image: 'ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/your-repo:latest'
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Environment:
            - Name: SPRING_DATASOURCE_URL
              Value: !Ref DatabaseUrl
            - Name: SPRING_DATASOURCE_USERNAME
              Value: root # Replace with Secrets Manager integration in prod
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: root # Replace with Secrets Manager integration in prod

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow traffic to ECS tasks
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0 # Note: In production, limit ingress to API Gateway/ALB

  EcsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref SecurityGroup

  ApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: backend-api
      ProtocolType: HTTP

  # API Gateway routes, integrations (VPC Link to ALB), and stages would be defined here
